#!/bin/sh

SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )";)

docker rm -f reverseproxy || true

docker run -d \
  --restart=always \
  --network=host \
  -v $SCRIPT_DIR/letsencrypt:/etc/letsencrypt \
  --name reverseproxy \
  reverseproxy
