#!/bin/sh

SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )";)

docker rm -f nginx || true

docker run -d \
  --restart=always \
  --network=host \
  -v $SCRIPT_DIR/letsencrypt:/etc/letsencrypt \
  --name nginx \
  redirects

  #-v $SCRIPT_DIR/nginx.settings:/etc/nginx/nginx.conf \
  #-v $SCRIPT_DIR/redirect.conf:/etc/nginx/conf.d/redirect.conf \
  #-v $SCRIPT_DIR/certbot-renew-crontab:/etc/crontabs/certbot-renew-crontab \
